### ISSUE TITLE
No CSS on Gitlab Pages

### ISSUE THREAD

**Issue by ghost** [tomanistor/osprey#48]
I wanted to host the website on Gitlab Pages, but the CSS is missing. For the CI, I used the default config from the Hugo example:

```
# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
```

The file is avaialbe on the [example page](https://gitlab.com/pages/hugo/blob/master/.gitlab-ci.yml) and my project is availabe [here](https://gitlab.com/JustMeErazem/justmeerazem.gitlab.io).
